#!/usr/bin/env python3
#	ecocalc - The X.509 Swiss Army Knife white-hat certificate toolkit
#	Copyright (C) 2017-2021 Johannes Bauer
#
#	This file is part of ecocalc.
#
#	ecocalc is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	ecocalc is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with ecocalc; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import sys
from FriendlyArgumentParser import FriendlyArgumentParser
from Economy import Economy
from Recipe import Recipe
from Tools import NumberTools

parser = FriendlyArgumentParser(description = "Print a recipes and the combination of them.")
parser.add_argument("-e", "--ecofile", metavar = "filename", type = str, required = True, help = "JSON definition file of the economy. Mandatory argument.")
parser.add_argument("-m", "--multiply", metavar = "value", default = [ ], action = "append", type = NumberTools.str2num, help = "Multiply all recipes with these coefficient(s). Can be specified multiple times. Fractions are allowed here.")
parser.add_argument("-g", "--gcd", metavar = "value", default = [ ], action = "append", type = int, help = "Multiply all recipes with the reciprocal of the gcd of all given values. Must be specified multiple times. Only integer values are allowed.")
parser.add_argument("--show-scaled", action = "store_true", help = "Show scaled rates and amounts instead of a multiplicity along with the base recipe.")
parser.add_argument("-p", "--show-rate", action = "store_true", help = "Show production rate, not item cardinality (i.e., resources per time instead of resources).")
parser.add_argument("-r", "--recurse", action = "store_true", help = "Recursively look up dependent resources and construct recipe path this way.")
parser.add_argument("-x", "--exclude-recipe", metavar = "recipe_no", type = int, action = "append", default = [ ], help = "Exclude specific recipe by its number. Can be specified multiple times.")
parser.add_argument("-c", "--consider-irreducible", metavar = "resource_name", type = str, action = "append", default = [ ], help = "Consider the given resource name as an irreducible resource. Can be specified multiple times.")
parser.add_argument("-l", "--limits", action = "store_true", help = "Determine the limits of a particular resource.")
parser.add_argument("--no-rounding", action = "store_true", help = "Do not round values.")
parser.add_argument("-v", "--verbose", action = "count", default = 0, help = "Increases verbosity. Can be specified multiple times.")
parser.add_argument("recipe", metavar = "recipe", type = str, nargs = "*", help = "Recipe descriptor(s). Can have multiple forms: '[coefficient] (name)', such as '150%% #1' or '1.75 smelt_iron' or 'smelt_copper'. When name starts with '#', it refers to the recipe by its number. When name starts with '>', descriptor selects a pseudo-recipe that requires a specific resource. If argument is omitted entirely, all recipes are enumerated.")
args = parser.parse_args(sys.argv[1:])

eco = Economy.from_args(args)
if len(args.recipe) == 0:
	recipes = eco.all_recipes
	print_sum = False
else:
	recipes = [ eco.get_recipe_by_descriptor(descriptor) for descriptor in args.recipe ]
	print_sum = True


multiply_coeff = 1
for coeff in args.multiply:
	multiply_coeff *= coeff

if len(args.gcd) > 0:
	gcd = NumberTools.gcd(args.gcd)
	multiply_coeff /= gcd

rate_suffix = "min" if args.show_rate else None

for recipe in recipes:
	print("%s" % ((recipe * multiply_coeff).pretty_string(eco, rate_suffix = rate_suffix, show_scaled = args.show_scaled, round_values = not args.no_rounding)))

if print_sum:
	print("=" * 120)
	sum_recipe = Recipe.empty_recipe()
	for recipe in recipes:
		sum_recipe = sum_recipe + recipe
	print("    %s" % ((sum_recipe * multiply_coeff).pretty_string(eco, rate_suffix = rate_suffix, show_scaled = args.show_scaled, round_values = not args.no_rounding)))

	limit_recipe = sum_recipe
	if args.recurse:
		print("~" * 120)
#		excluded_recipe_indices = set((recipe_number - 1) for recipe_number in args.exclude_recipe)
		resolved = eco.resolve_recursively(sum_recipe)
		limit_recipe = resolved.recipe
		for application in resolved.grouped_applications:
			print("    %s" % ((application.recipe * application.scalar * multiply_coeff).pretty_string(eco, rate_suffix = rate_suffix, show_scaled = args.show_scaled, round_values = not args.no_rounding)))
		print(" -> %s" % ((resolved.recipe * multiply_coeff).pretty_string(eco, rate_suffix = rate_suffix, show_scaled = True, round_values = not args.no_rounding)))

if print_sum and args.limits:
	print()
	sorted_list = [ (eco.get_resource_sort_order(ingredient.name), ingredient) for ingredient in limit_recipe.ingredients ]
	sorted_list.sort()
	quantities = { }
	productions = { }
	min_production = None
	for (sort_key, ingredient) in sorted_list:
		name = eco.get_resource_name(ingredient.name)
		quantity = input("%-10s: " % (name))
		if quantity == "":
			continue
		try:
			quantity = int(quantity)
		except ValueError:
			quantity = round(float(quantity))
		quantities[ingredient.name] = quantity
		productions[ingredient.name] = quantity // ingredient.count
		if (min_production is None) or (productions[ingredient.name] < min_production):
			min_production = productions[ingredient.name]
			limited_by = name

	print("Minimal production: %s (limited by %s)" % (NumberTools.unify(min_production), limited_by))
	for (sort_key, ingredient) in sorted_list:
		name = eco.get_resource_name(ingredient.name)
		if ingredient.name not in quantities:
			print("%-15s Unlimited" % (name))
		else:
			remaining = quantities[ingredient.name] - (min_production * ingredient.count)
			print("%-15s %-10s -> %-10s utilization %5.1f%% remaining %s" % (name, NumberTools.unify(quantities[ingredient.name]), NumberTools.unify(productions[ingredient.name]), 100 * min_production / productions[ingredient.name], NumberTools.unify(remaining)))
