#!/usr/bin/python3
import re
import sys

stripit = [ "DG" ]

for line in sys.stdin:
	if not line.startswith("SR-"):
		continue

	line1 = line.rstrip()
	line2 = sys.stdin.readline().rstrip()

	line1 = line1.split("\t")
	line2 = line2.split("\t")
	item_name = line1[1]
	item_id = line2[0]
	value = line2[2]
	
	item_name = item_name.strip()
	item_id = item_id.strip().lower()
	item_id = item_id.strip("()")
	value = int(value.strip())

	cont = True
	while cont:
		cont = False
		for stripval in stripit:
			if item_name.endswith(stripval):
				item_name = item_name[:-len(stripval)].strip()
				cont = True
	
	print("%s (%s) = %d" % (item_name, item_id, value))

